
---
- hosts: localhost
  connection: local
  tasks:
    - name: Stop Instances
      ec2_instance_facts:
        region: ap-south-1
      register: ec2_info
 
    - name: displaying output
      debug: msg="{{item.instance_id}}"
      with_items: "{{ec2_info.instances}}"
 
    - name: terminate
      ec2:
        instance_ids: "{{item.instance_id}}"
        region: us-east-2
        state: Stopped
        wait: yes
      with_items: "{{ec2_info.instances}}"
